import React from "react";
import Navbar from "./Navbar";

function About() {
  return (
    <div>
      <Navbar />
      <div className="w-4/5 mx-auto mt-14 bg-white px-14 py-4 rounded gap-10">
        <p>
          This is a sample page generated by me for the purpose of evaluating
          various options for further work. It has all the details which we need
          to build upon a concept and explore it further as well.
        </p>
      </div>
    </div>
  );
}

export default About;
